name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v4
    
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
        
    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.target }}
        
    - name: Install cross-compilation tools
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
        
    - name: Configure cross-compilation
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        mkdir -p .cargo
        cat > .cargo/config.toml << EOF
        [target.aarch64-unknown-linux-gnu]
        linker = "aarch64-linux-gnu-gcc"
        EOF
        
    - name: Build for ${{ matrix.target }}
      run: cargo build --release --target ${{ matrix.target }}
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/${{ matrix.target }}/release/xm125-radar-monitor
        name: Release ${{ github.ref_name }}
        body: |
          ## XM125 Radar Monitor ${{ github.ref_name }}
          
          ### 🔧 Critical Configuration Fixes
          
          #### ✅ Range Configuration Fixed
          - **FIXED**: End Point register now correctly holds 5500mm (not 2500mm default)
          - **FIXED**: Configuration sequence ensures range values persist after apply command
          - **FIXED**: Module reset properly implemented for clean baseline (0.00m start)
          - **IMPROVED**: Range values written AFTER profile settings to prevent overwriting
          
          #### 🎯 Proper Reset Sequence
          - **ADDED**: Module reset before configuration (CMD_PRESENCE_RESET_MODULE: 1381192737)
          - **ADDED**: Wait for reset completion before applying configuration
          - **VERIFIED**: Clean 0.00m baseline after reset (no carryover from previous state)
          
          #### 📊 Configuration Validation
          - **VERIFIED**: Start Point register: 0x0000012C (300mm) ✅
          - **VERIFIED**: End Point register: 0x0000157C (5500mm) ✅ 
          - **VERIFIED**: Full 0.3m-5.5m detection range now available
          - **TESTED**: Proper configuration sequence on target hardware
          
          #### 🚀 Production Ready
          - **CONFIRMED**: XM125 presence detection system fully operational
          - **VALIDATED**: Complete datasheet-compliant configuration process
          - **READY**: For deployment with verified 5.5m maximum range capability
          
          ### 📦 Build Artifacts
          
          - `xm125-radar-monitor-x86_64-unknown-linux-gnu`: Native Linux x86_64 binary
          - `xm125-radar-monitor-aarch64-unknown-linux-gnu`: ARM64 Linux binary (for Sentai board)
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
